---

- name: install dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packags:
      - make
      - gcc
      - libcurl4-openssl-dev
      - libexpat1-dev
      - gettext
      - libz-dev
      - libssl-dev
      - perl-modules
  become: yes

- name: clear state
  file:
    path: /tmp/git-{{ git_version }}
    state: absent
  become: yes

- name: fetch git-scm
  unarchive:
    src: https://www.kernel.org/pub/software/scm/git/git-{{ git_version }}.tar.gz
    dest: /tmp
    remote_src: yes

- name: configure
  command: ./configure
  args:
    chdir: /tmp/git-{{ git_version }}

- name: make
  command: make -j{{ ansible_processor_vcpus }} prefix=/usr/local all
  args:
    chdir: /tmp/git-{{ git_version }}

- name: install
  command: make prefix=/usr/local install
  args:
    chdir: /tmp/git-{{ git_version }} 
  become: yes
