---

- name: get current git version
  command: /usr/local/bin/git --version
  register: git_current
  ignore_errors: yes

- import_tasks: compile.yml
  when: git_current.rc != 0 or not git_current.stdout | search(git_version_string_match)
